In [1]:
import pandas as pd
import numpy as np

pd.options.display.max_columns = None
#https://www.youtube.com/watch?v=jFCwNXAEGpA
#https://statusinvest.com.br/acoes/busca-avancada

In [2]:
#EV/EBIT 0,01
#Liquidez média diária 250.000,00
#Valor de mercado  250.000.000,00

data =  pd.read_csv('statusinvest-busca-avancada-2023-01-06.csv', sep=';',encoding='latin-1')
columns = data.columns
columns

Index(['TICKER', 'PRECO', 'DY', 'P/L', 'P/VP', 'P/ATIVOS', 'MARGEM BRUTA',
       'MARGEM EBIT', 'MARG. LIQUIDA', 'P/EBIT', 'EV/EBIT',
       'DIVIDA LIQUIDA / EBIT', 'DIV. LIQ. / PATRI.', 'PSR', 'P/CAP. GIRO',
       'P. AT CIR. LIQ.', 'LIQ. CORRENTE', 'ROE', 'ROA', 'ROIC',
       'PATRIMONIO / ATIVOS', 'PASSIVOS / ATIVOS', 'GIRO ATIVOS',
       'CAGR RECEITAS 5 ANOS', 'CAGR LUCROS 5 ANOS', ' LIQUIDEZ MEDIA DIARIA',
       ' VPA', ' LPA', ' PEG Ratio', ' VALOR DE MERCADO'],
      dtype='object')

In [3]:
cod = data['TICKER'].to_numpy()
len(cod)

249

In [4]:
data = data.sort_values(by=["EV/EBIT"])
data.head(10)

,TICKER,PRECO,DY,P/L,P/VP,P/ATIVOS,MARGEM BRUTA,MARGEM EBIT,MARG. LIQUIDA,P/EBIT,EV/EBIT,DIVIDA LIQUIDA / EBIT,DIV. LIQ. / PATRI.,PSR,P/CAP. GIRO,P. AT CIR. LIQ.,LIQ. CORRENTE,ROE,ROA,ROIC,PATRIMONIO / ATIVOS,PASSIVOS / ATIVOS,GIRO ATIVOS,CAGR RECEITAS 5 ANOS,CAGR LUCROS 5 ANOS,LIQUIDEZ MEDIA DIARIA,VPA,LPA,PEG Ratio,VALOR DE MERCADO
216,SYNE3,"4,16","209,45","0,52","0,41","0,15","69,60","67,81","53,26","0,41","0,80","0,39","0,40","0,27","1,03","-0,18","6,61","79,34","29,28","39,56","0,37","0,36","0,55","40,50",NaN,"1.654.024,35","10,16","8,06","0,00","635.000.891,20"
103,GOAU4,"13,57","9,21","2,98","0,84","0,17","24,43","22,94","5,47","0,71","0,88","0,19","0,23","0,16","0,66","-0,33","2,28","28,16","5,86","25,12","0,21","0,38","1,07","15,78",NaN,"133.185.521,35","16,15","4,55","0,30","13.474.250.684,76"
102,GOAU3,"12,05","10,37","2,65","0,75","0,16","24,43","22,94","5,47","0,63","0,88","0,19","0,23","0,14","0,58","-0,30","2,28","28,16","5,86","25,12","0,21","0,38","1,07","15,78",NaN,"3.025.056,88","16,15","4,55","0,27","13.474.250.684,76"
82,ENAT3,"12,17","14,04","3,63","0,81","0,53","41,49","65,20","40,46","2,25","1,54","-0,71","-0,26","1,47","4,40","-0,75","1,69","22,40","14,63","22,43","0,65","0,35","0,36","30,52","42,30","24.093.742,38","14,98","3,36","0,09","3.234.870.033,85"
137,LVTC3,"5,40","3,22","7,62","0,54","0,21","24,78","10,16","4,29","3,21","1,56","-1,65","-0,28","0,33","0,61","-0,50","2,37","7,08","2,71","14,97","0,38","0,62","0,63",NaN,NaN,"944.988,62","10,02","0,71","-0,19","349.180.540,20"
22,BAZA3,"51,99","13,21","2,56","0,65","0,09","35,57","61,66","39,79","1,65","1,65",NaN,NaN,"1,02","0,94","-0,10",NaN,"25,51","3,49",NaN,"0,14","0,86","0,09","-2,61","54,23","323.614,00","79,74","20,34","0,03","2.914.471.796,85"
34,BRAP4,"28,94","31,60","1,92","1,45","1,44",NaN,NaN,NaN,"1,93","1,71","-0,14","-0,11",NaN,"14,27","-1,62","9,56","75,82","74,92","74,47","0,99","0,01","0,00",NaN,"56,67","143.352.629,92","19,93","15,11","0,21","10.936.028.118,78"
33,BRAP3,"25,75","32,28","1,70","1,29","1,28",NaN,NaN,NaN,"1,72","1,71","-0,14","-0,11",NaN,"12,69","-1,44","9,56","75,82","74,92","74,47","0,99","0,01","0,00",NaN,"56,67","3.729.517,92","19,93","15,11","0,19","10.936.028.118,78"
234,USIM5,"7,57","10,86","1,89","0,39","0,23","21,12","18,02","15,23","1,60","1,76","0,16","0,04","0,29","0,60","-0,47","4,16","20,61","12,24","14,14","0,59","0,34","0,80","31,89",NaN,"153.004.971,81","19,39","4,00","-0,05","9.443.493.206,52"
233,USIM3,"7,51","9,95","1,88","0,39","0,23","21,12","18,02","15,23","1,59","1,76","0,16","0,04","0,29","0,60","-0,47","4,16","20,61","12,24","14,14","0,59","0,34","0,80","31,89",NaN,"3.839.413,81","19,39","4,00","-0,05","9.443.493.206,52"

In [5]:
data["point"] = 1
data["pointEV/EBIT"] = data['point'].cumsum()

In [6]:
data = data.sort_values(by=["ROIC"], ascending=False)
data["pointROIC"] = data['point'].cumsum()

In [7]:
data["pointFinal"] = data["pointEV/EBIT"] + data["pointROIC"]

In [8]:
data = data.sort_values(by=["pointFinal"])

In [15]:
data.head(100)

,TICKER,PRECO,DY,P/L,P/VP,P/ATIVOS,MARGEM BRUTA,MARGEM EBIT,MARG. LIQUIDA,P/EBIT,EV/EBIT,DIVIDA LIQUIDA / EBIT,DIV. LIQ. / PATRI.,PSR,P/CAP. GIRO,P. AT CIR. LIQ.,LIQ. CORRENTE,ROE,ROA,ROIC,PATRIMONIO / ATIVOS,PASSIVOS / ATIVOS,GIRO ATIVOS,CAGR RECEITAS 5 ANOS,CAGR LUCROS 5 ANOS,LIQUIDEZ MEDIA DIARIA,VPA,LPA,PEG Ratio,VALOR DE MERCADO,point,pointEV/EBIT,pointROIC,pointFinal
210,SOJA3,"10,09","1,08","10,03","1,61","0,71","10,12","8,27","7,93","9,63","10,15","0,52","0,09","0,80","2,72","-2,43","1,58","16,08","7,03","9,42","0,44","0,52","0,89",NaN,NaN,"3.148.043,96","6,25","1,01","-0,76","1.181.945.889,34",1,17,9,26
60,CPLE6,"7,82","12,70","24,36","1,02","0,43","21,07","13,04","3,84","7,17","10,02","3,02","0,43","0,93","5,71","-0,55","1,54","4,19","1,76","8,15","0,42","0,57","0,46","12,85","-0,39","151.611.125,38","7,66","0,32","-0,29","20.896.324.435,00",1,11,23,34
58,CPLE11,"38,18","12,77","23,79","1,00","0,42","21,07","13,04","3,84","7,00","10,02","3,02","0,43","0,91","5,58","-0,53","1,54","4,19","1,76","8,15","0,42","0,57","0,46","12,85","-0,39","23.495.433,69","38,31","1,60","-0,28","20.896.324.435,00",1,13,22,35
34,BRAP4,"28,94","31,60","1,92","1,45","1,44",NaN,NaN,NaN,"1,93","1,71","-0,14","-0,11",NaN,"14,27","-1,62","9,56","75,82","74,92","74,47","0,99","0,01","0,00",NaN,"56,67","143.352.629,92","19,93","15,11","0,21","10.936.028.118,78",1,7,29,36
33,BRAP3,"25,75","32,28","1,70","1,29","1,28",NaN,NaN,NaN,"1,72","1,71","-0,14","-0,11",NaN,"12,69","-1,44","9,56","75,82","74,92","74,47","0,99","0,01","0,00",NaN,"56,67","3.729.517,92","19,93","15,11","0,19","10.936.028.118,78",1,8,28,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,FESA4,"57,28","7,68","4,41","1,66","1,27","50,23","41,83","36,91","3,89","3,60","-0,38","-0,16","1,63","3,97","-2,24","3,94","37,72","28,87","32,81","0,77","0,23","0,78","16,87","75,11","11.975.705,27","34,43","12,99","0,03","5.168.486.400,00",1,118,87,205
229,TUPY3,"27,43","1,38","7,69","1,27","0,44","18,24","8,02","5,33","5,11","7,11","2,00","0,50","0,41","1,04","-1,37","2,66","16,55","5,73","9,67","0,35","0,65","1,08","16,82",NaN,"28.920.128,54","21,55","3,57","0,06","3.954.788.825,00",1,207,3,210
95,FLRY3,"15,95","5,04","14,59","2,65","0,75","28,29","17,90","7,97","6,49","10,13","3,64","1,48","1,16","10,07","-1,02","1,38","18,16","5,13","11,83","0,28","0,72","0,64","13,06","8,74","49.760.601,35","6,02","1,09","-0,86","5.074.299.186,00",1,16,194,210
108,HBSA3,"2,47",NaN,"-48,02","1,39","0,29","28,69","14,86","-2,60","8,40","26,61","18,21","3,01","1,25","2,98","-0,37","1,97","-2,89","-0,61","3,06","0,21","0,79","0,24","23,22",NaN,"12.644.423,73","1,78","-0,05","0,73","1.878.145.128,21",1,108,102,210
131,LIGT3,"5,00","5,07","-17,63","0,22","0,07","18,66","10,91","-0,73","1,18","5,91","4,73","0,87","0,13","0,90","-0,10","1,33","-1,22","-0,38","7,91","0,31","0,69","0,52","9,08",NaN,"26.286.837,65","23,16","-0,28","0,15","1.862.776.620,00",1,179,31,210

In [17]:
data.to_csv('09-12-2022x')